### ISSUE TITLE
Add Favicon to the webpage

### ISSUE THREAD

**Issue by shrinish123** [shrinish123/GuessMovie#10]
We need to add a favicon to the website to make it look attractive

**Comment by munal0803** [comment]
sir i will like to contribute to this issue

**Comment by shrinish123** [comment]
Don't call me sir, I'm just another guy like you. Sure I will assign this to you.

**Comment by munal0803** [comment]
thanks @shrinish123

**Comment by Rajdeep-G** [comment]
Is this issue still available ?

**Comment by shrinish123** [comment]
@Rajdeep-G  actually I already assigned this to @munal0803, You can surely work on other issues

**Comment by dollyjain51099** [comment]
I want to work on this issue can u please assign it to me.
