### ISSUE TITLE
apikey should be a secret

### ISSUE THREAD

**Issue by j-tesla** [shrinish123/GuessMovie#16]
https://github.com/shrinish123/GuessMovie/blob/3d6e7f023485a00fc0a45305b997ae5a020dbee0/src/utils/movieSearch.js#L6

It is not a good idea to embed api key in the code, especially when you are putting your code in public.
As the number of api calls per api calls is limited and many people using the same api key may cause problems. 
It is better to store apikey as an environment variable and add instructions to developers to get their own api key. (it ain't that hard)

**Comment by j-tesla** [comment]
@shrinish123 if you agree, you can assign me to this issue

**Comment by shrinish123** [comment]
Ya, I even read about it But had no idea about how to do it. It would be great if you implement this and also provide me  instructions on how to do this and also update the README for other people to get the instructions on how to run this
Dont tell me here separately , only Update the Readme I will get that from the README
