### ISSUE TITLE
Update header section

### ISSUE THREAD

**Issue by tejan-singh** [shrinish123/GuessMovie#17]
- I would like to add styling and background colour to heading and search box to improve UI.

**Comment by dollyjain51099** [comment]
I want to work on this issue can u please assign it to me.

**Comment by shrinish123** [comment]
@tejan-singh  I am assigning this to you, all the best for contributing to this project

**Comment by shrinish123** [comment]
@dollyjain51099  can you take the designing the game page issue, because the ones I had assigned, probably are not responding
Just comment on the issue I will assign you the issue and also provide you the directions of how should be the basic structure of the game page
