### ISSUE TITLE
Browser is not informed if the requested query is not found

### ISSUE THREAD

**Issue by j-tesla** [shrinish123/GuessMovie#20]
https://github.com/shrinish123/GuessMovie/blob/990d9e9981d37f0db323c1d535ec61b387e3da60/src/app.js#L45

In case of failing to find the requested query, error is printed to server's console but response with 404 status is not sent thy browser. So, browser keeps waiting for the response.

**Comment by shrinish123** [comment]
Ya, surely you can work on this. All the best

**Comment by j-tesla** [comment]
> Ya, surely you can work on this. All the best 

I'll start shortly
